// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ujznybsuiphisibdnyob.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVqem55YnN1aXBoaXNpYmRueW9iIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mzk2MDAyMTAsImV4cCI6MjA1NTE3NjIxMH0.FojLWlV_tSjkhLXsta9lvbwaV72EbXvcouOZQVq9d3Q";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);